AWSTemplateFormatVersion : '2010-09-09'
Description: "Custome Template : TrustLogin-Lambda"

Parameters:
  CK:
    Description: "Consumer Key (API Key)"
    Type: String
  CS:
    Description: "Consumer Secret (API Secret)"
    Type: String
  AT:
    Description: "Access Token"
    Type: String
  AS:
    Description: "Access Token Secret"
    Type: String

Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: Intro_tweetbot
      Description: ""
      Runtime: python3.6
      Handler: lambda_function.my_handler
      Code: src
      Environment:
        Variables:
          CK: !Ref CK
          CS: !Ref CS
          AT: !Ref AT
          AS: !Ref AS
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt IAMRoleForLambda.Arn

  #-------- Lambda Permission --------#
  PermissionForEventsToInvokeLambdaFunction:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CloudWatchEventsRuleForExportLambdaFunction.Arn

  #-------- CloudWatch Event Rule--------#
  CloudWatchEventsRuleForExportLambdaFunction:
    Type: AWS::Events::Rule
    Properties:
      Description: tweet today's house musicians name everyday.
      Name: Intro_tweet_bot
      ScheduleExpression: "cron(00 9 * * ? *)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: TargetFunctionV1

  #-------- IAM Role --------#
  IAMRoleForLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      Path: /
      Policies:
        -
          PolicyName: IAMPolicyForLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Action: logs:*
                Effect: Allow
                Resource: "*"
      RoleName: IAMRoleForLambda
