service: webscraping-with-selenium

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  timeout: 900
  environment:
    SELENIUM_LAYER_SERVICE: selenium-layer

functions:
  introTweetBot:
    memorySize: 512
    timeout: 15
    handler: lambda_function.my_handler
    events:
      - schedule:
          rate: cron(0 3 * * ? *)
    layers:
      - ${cf:${self:provider.environment.SELENIUM_LAYER_SERVICE}-${opt:stage, self:provider.stage}.SeleniumLayerExport}
      - ${cf:${self:provider.environment.SELENIUM_LAYER_SERVICE}-${opt:stage, self:provider.stage}.ChromedriverLayerExport}